routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These  routes are loaded by the RouteServiceProvider within a group which  contains the "web" middleware group. Now create something great!
*/

Route::get('/', 'TestController@welcome');


Route::get('/prueba', function () {
    return 'Hola soy una ruta de prueba';
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/logout', 'HomeController@logout')->name('logout');

Route::get('/search', 'SearchController@show');
Route::get('/products/json', 'SearchController@data');


//Parte del Publico, esta parte esta accesible por cualquier usuario que este logueado.
Route::get('/products/{id}', 'ProductController@show'); // muestra
Route::get('/categories/{miCategoria}', 'CategoryController@show'); // Aqui enviamos miCategoria al controlador CategoryController

Route::post('/cart', 'CartDetailController@store'); // Graba un producto en el carrito
Route::delete('/cart', 'CartDetailController@destroy'); // Elimina un articulo del carrito


Route::post('/order', 'CartController@update'); // graba el Pedido.


//Parte del Administrador, tanto las vistas como controladores esta organizado en la carpeta admin.
//Con el middleware nos aseguramos que el usuario esta autenticado y ademas tiene la marca de Admin = 1. Si no es así lo devuelve a la pag. de inicio.
Route::middleware(['auth', 'admin'])->prefix('admin')->namespace('Admin')->group(function () {
   
      //Aqui ya estamos suponiendo que estamos dentro de la carpeta admin:
      Route::get('/categories', 'CategoryController@index'); //Muesta los articulos de 10 en 10 gracias a la vista: view('admin.products.index');
      Route::get('/categories/create', 'CategoryController@create'); // Muestra un formulario para dar de alta Articulos gracias a la vista; view('admin.products.create');
      Route::get('/categories/{category}/edit', 'CategoryController@edit'); // Muestra un formulario para modificar Articulos ya existentes = view('admin.products.edit');
      Route::post('/categories', 'CategoryController@store'); // Este metodo del controlador es el que graba realmente el articulo en la BBDD cuando se lo solicita view('admin.products.create') mediante el formulario POST;
      Route::post('/categories/{category}/edit', 'CategoryController@update'); // Igual que el anterior, actualiza el articulo en la BBDD despues de que view('admin.products.edit') se lo solicite mediante el fomulario por metodo POST;
      Route::delete('/categories/{category}', 'CategoryController@destroy'); // Localiza el articulo mediante el $id y lo elimina de la BBDD

    //Poniendo el namespace se puede quitar el Admin  del ProductController = Route::get('/products', 'Admin\ProductController@index'); 

    //Aqui ya estamos suponiendo que estamos dentro de la carpeta admin:
    Route::get('/products', 'ProductController@index'); //Muesta los articulos de 10 en 10 gracias a la vista: view('admin.products.index');
    Route::get('/products/create', 'ProductController@create'); // Muestra un formulario para dar de alta Articulos gracias a la vista; view('admin.products.create');
    Route::get('/products/{id}/edit', 'ProductController@edit'); // Muestra un formulario para modificar Articulos ya existentes = view('admin.products.edit');
    Route::post('/products', 'ProductController@store'); // Este metodo del controlador es el que graba realmente el articulo en la BBDD cuando se lo solicita view('admin.products.create') mediante el formulario POST;
    Route::post('/products/{id}/edit', 'ProductController@update'); // Igual que el anterior, actualiza el articulo en la BBDD despues de que view('admin.products.edit') se lo solicite mediante el fomulario por metodo POST;
    Route::delete('/products/{id}', 'ProductController@destroy'); // Localiza el articulo mediante el $id y lo elimina de la BBDD
  
    // Route::get('/admin/products', 'Admin\ProductController@index'); //listado inicio
    // Route::get('/admin/products/create', 'Admin\ProductController@create'); // crear
    // Route::post('/admin/products', 'Admin\ProductController@store'); // crear
    // Route::get('/admin/products/{id}/edit', 'Admin\ProductController@edit'); // editar
    // Route::post('/admin/products/{id}/edit', 'Admin\ProductController@update'); // actualizar
    // Route::delete('/admin/products/{id}', 'Admin\ProductController@destroy'); // eliminar

    Route::get('/products/{id}/images', 'ImageController@index'); // Lista las imagenes asociadas al articulo que se pasa por $id
    Route::post('/products/{id}/images', 'ImageController@store'); //Sube una imagen a nuestro sitio web (carpeta /images/products) y la graba en la bbdd.

    // 
    Route::get('/products/{id}/images/select/{image}', 'ImageController@select'); // Busca un producto, y marca como destacada la imagen pasada como parametros.
    Route::delete('/products/{id}/images', 'ImageController@destroy'); // Elimina las imágenes.

});

//Es lo mismo que arriba pero abreviado.
Route::get('inicio', 'ProductController@index')->name('inicio'); //listado de inicio = Route::get('/admin/products', 'ProductController@index'); 
Route::get('productos', 'ProductController@index')->name('productos'); 

Route::post('editar/{id}', 'ProductController@update')->name('editar'); // actualizar
Route::post('borrar/{id}', 'ProductController@destroy')->name('borrar'); // Eliminar

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    
    public static $messages = [
        'name.required' => 'Necesita rellenar el nombre.',
        'name.min' => 'Minimo 3 caracteres.',             
        'description.required' => 'Necesita rellenar la descripción.',
        'description.min' => 'Minimo 15 caracteres.',              
        'price.required' => 'El precio es obligatorio.', 
        'price.min' => 'El precio es obligatorio.',               
    ];
   
    public static $rules = [
        'name' =>  'required|min:3',
        'description' =>  'required|max:200',
        'price' =>  'required|numeric|min:0'
    ];
    
    // Para ver a que categoria pertenece un producto
    public function category()
    {
        // Un producto pertenece a 1 categoria
        return $this->belongsTo(Category::class);
    }

    // Para acceder a las imagenes
    public function images()
    {
        // Un producto tiene muchas fotos
        return $this->hasMany(ProductImage::class);
    }

    public function getFeaturedImageUrlAttribute(){
        
        $featuredImage = $this->images()->where('featured', true)->first();

        if (!$featuredImage)
            $featuredImage = $this->images()->first();            

        if ($featuredImage) {
            return $featuredImage->url;
        }

        return  public_path().'/images/products/default.jpg';
    }

    public function getCategoryNameAttribute()
    {
            if ($this->category)
                return $this->category->name;
            
            return 'General';
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Category;
use App\Product;

class ProductController extends Controller
{
    // Muestra los primeros 10 articulos.
    public function index(){
       // $misProductos = Product::all();
       $misProductos = Product::paginate(10);
    //    $miProducto = DB::select("select name from products where id = 1");
    //    dd($miProducto);      
        
       return view('admin.products.index')->with('MisProductos', $misProductos);
        //return view('admin.products.index')->with(compact('products'));
        
    }

    public function create(){

        $categories = Category::orderBy('name')->get();
        return view('admin.products.create')->with(compact('categories')); //formulario de registro.
    }

    public function store(Request $request){
        //registrar el nuevo producto en la bbdd


        $this->validate($request, Product::$rules, Product::$messages);    

        $mProducto = new Product();
        $mProducto->name = $request->input('name');
        $mProducto->description = $request->input('description');
        $mProducto->price = $request->input('price');
        $mProducto->long_description = $request->input('long_description');
        $mProducto->category_id = $request->category_id;
        $mProducto->save(); // INSERT EN PRODUCTOS

        return redirect("/admin/products");
    }

    public function edit($id)
    {
       // return "Mostrar ID: $id";
        $categories = Category::orderBy('name')->get();

        $miProducto = Product::find($id);
        //return view('admin.products.edit')->with('miProducto', $miProducto); //form de edicion
        return view('admin.products.edit')->with(compact('miProducto', 'categories'));//form de edicion
    }

    public function update(Request $request, $id)
    {
        // $messages = [
        //     'name.required' => 'Necesita rellenar el nombre',
        //     'name.min' => 'Nombre: Minimo 3 caracteres',             
        //     'description.required' => 'Necesita rellenar la descripción',
        //     'description.min' => 'Descripción: Minimo 15 caracteres',              
        //     'price.required' => 'El precio es obligatorio', 
        //     'price.min' => 'El precio no puede ser negativo',               
        //     'price.numeric' => 'Ingrese un precio valido',
        //     'long_description.required' => 'Rellene la descripción larga'
        // ];
       
        // $rules = [
        //     'name' =>  'required|min:3',
        //     'description' =>  'required|max:200|min:15',
        //     'price' =>  'required|numeric|min:0',
        //     'long_description' =>  'required|max:200|min:15'
        // ];

        $this->validate($request, Product::$rules, Product::$messages);   

        $mProducto = Product::find($id);
        $mProducto->name = $request->input('name');
        $mProducto->description = $request->input('description');
        $mProducto->price = $request->input('price');
        $mProducto->long_description = $request->input('long_description');
        $mProducto->category_id = $request->category_id;
        $mProducto->save(); // UPDATE EN PRODUCTOS

        return redirect("/admin/products");
    }

    public function destroy($id)
    {
        $miProducto = Product::find($id);

        
        $miProducto->delete(); // DELETE EN PRODUCTOS

        return back();
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;

class ProductController extends Controller
{
    public function show($id){

        $product = Product::find($id);
        $images = $product->images;

        $imagesLeft = collect();
        $imagesRight = collect();

        $i = 0;

        foreach ($images as $image) {
        
            if ($i%2==0)
                $imagesLeft->push($image);
            else
                $imagesRight->push($image);

            $i++;
        }    

        return view('products.show')->with(compact('product', 'imagesLeft', 'imagesRight'));

        //
    }

}

resources/views/products/show.blade.php
@extends('layouts.app')

@section('title', 'Marcador CryptoZone ')

@section('body-class', 'profile-page')

@section('contenido')


		<div class="header header-filter" style="background-image: url('/img/examples/city.jpg');"></div>

		<div class="main main-raised">
			<div class="profile-content">
	            <div class="container">
	                <div class="row">
	                    <div class="profile">
	                        <div class="avatar">
	                            <img src="{{ $product->featured_image_url }}" alt="Circle Image" class="img-circle img-responsive img-raised">
	                        </div>
							
								<!-- Si existe la variable notificacion, la pinta -->
								@if (session('notificacion'))
								<br/>
                        			<div class="alert alert-success" role="alert">
                            			{{ session('notificacion') }}
                        			</div>
                    			@endif

	                        <div class="name">
	                            <h3 class="title"> {{ $product->name }} </h3>
								<h6> {{ $product->category->name }} </h6>
	                        </div>
	                    </div>
	                </div>
	                <div class="description text-center">
                        <p> {{ $product->long_description }} </p>
	                </div>

					<div class="text-center">
						<button class="btn btn-primary btn-round"  data-toggle="modal" data-target="#ModalAddToCart"> 
							<i class="material-icon">+</i> Añadir Carrito
						</button>
					</div>

							

					<div class="row">
						<div class="col-md-6 col-md-offset-3">
							<div class="profile-tabs">
			                    <div class="nav-align-center">
									
				                    <div class="tab-content gallery">
										<div class="tab-pane active" id="studio">
				                            <div class="row">
												<div class="col-md-6">
													@foreach ($imagesLeft as $image)
														<img src=" {{ $image->url }} " class="img-rounded" />
													@endforeach
												</div>
												 <div class="col-md-6">
													@foreach ($imagesRight as $image)
														<img src=" {{ $image->url }} " class="img-rounded" />
													@endforeach
													
													
												</div>
				                            </div>
				                        </div>
				                	</div>
								</div>
							</div>
							<!-- End Profile Tabs -->
						</div>
	                </div>

	            </div>
	        </div>
		

    </div>

<!-- Modal Core -->
<div class="modal fade" id="ModalAddToCart" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
						<div class="modal-dialog">
							<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
								<h4 class="modal-title" id="myModalLabel">Seleccione la cantidad</h4>
							</div>

							<form method="post" action="{{ url('/cart') }}">
								{{ csrf_field() }}
								<input type="hidden" name="product_id" value="{{ $product->id }}" >						
								<div class="modal-body">
								<input type="number" name="quantity" value="1" class="form-control">						
								</div>
								<div class="modal-footer">
									<button type="button" class="btn btn-default btn-simple" data-dismiss="modal">Cancelar</button>
									<button type="submit" class="btn btn-info btn-simple">Añadir al Carrito</button>
								</div>

							</form>
							
							</div>
						</div>
					</div>
@include('includes.footer')	   
        
@endsection